docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Intro: intro.md
    - ClassFileLocator: class-file-locator.md
site_name: zend-file
site_description: zend-file
repo_url: 'https://github.com/zendframework/zend-file'
copyright: 'Copyright (c) 2005-2018 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
